services:

  _defaults:
    autowire: true
    autoconfigure: true

  App\EventSystem\RawValueToNormalizedValue\EventListener\DateTimeRawValueToNormalizedValueEventListener:
    tags:
      - name: kernel.event_listener
        event: 'App\EventSystem\RawValueToNormalizedValue\Event\RawValueToNormalizedValueEvent'
        method: 'onRawValueToNormalizedValueEvent'
        priority: 16

  App\EventSystem\RawValueToNormalizedValue\EventListener\GenericRawValueToNormalizedValueEventListener:
    tags:
      - name: kernel.event_listener
        event: 'App\EventSystem\RawValueToNormalizedValue\Event\RawValueToNormalizedValueEvent'
        method: 'onRawValueToNormalizedValueEvent'
        priority: 0
