services:

  _defaults:
    autowire: true
    autoconfigure: true

  App\EventSystem\EntityManager\EventListener\CreatedElementPreWriteEventListener:
    tags:
      - name: kernel.event_listener
        event: 'App\EventSystem\EntityManager\Event\ElementPreCreateEvent'
        method: 'onElementPreCreateEvent'
      - name: kernel.event_listener
        event: 'App\EventSystem\EntityManager\Event\ElementPreMergeEvent'
        method: 'onElementPreMergeEvent'

  App\EventSystem\EntityManager\EventListener\UpdatedElementPreWriteEventListener:
    tags:
      - name: kernel.event_listener
        event: 'App\EventSystem\EntityManager\Event\ElementPreCreateEvent'
        method: 'onElementPreCreateEvent'
      - name: kernel.event_listener
        event: 'App\EventSystem\EntityManager\Event\ElementPreMergeEvent'
        method: 'onElementPreMergeEvent'

  App\EventSystem\EntityManager\EventListener\OwnershipChangeEventListener:
    tags:
      - name: kernel.event_listener
        event: 'App\EventSystem\EntityManager\Event\ElementPostCreateEvent'
        method: 'onElementPostCreate'
      - name: kernel.event_listener
        event: 'App\EventSystem\EntityManager\Event\ElementPostMergeEvent'
        method: 'onElementPostMerge'
      - name: kernel.event_listener
        event: 'App\EventSystem\EntityManager\Event\ElementPostDeleteEvent'
        method: 'onElementPostDelete'

  App\EventSystem\EntityManager\EventListener\CalculateSearchAccessEventListener:
    tags:
      - name: kernel.event_listener
        event: 'App\EventSystem\EntityManager\Event\ElementPostCreateEvent'
        method: 'onElementPostCreate'
      - name: kernel.event_listener
        event: 'App\EventSystem\EntityManager\Event\ElementUpdateAfterBackupLoadEvent'
        method: 'onElementUpdateAfterBackupLoadEvent'

  App\EventSystem\EntityManager\EventListener\ExpireTokenOnTokenDeleteEventListener:
    tags:
      - name: kernel.event_listener
        event: 'App\EventSystem\EntityManager\Event\ElementPostDeleteEvent'
        method: 'onElementPostDeleteEvent'
