services:

  _defaults:
    autowire: true
    autoconfigure: true

  App\EventSystem\Exception\EventListener\ExceptionEventListener:
    tags:
      - name: kernel.event_listener
        event: 'kernel.exception'
        method: 'onKernelException'
