services:

  _defaults:
    autowire: true
    autoconfigure: true

  App\EventSystem\Kernel\EventListener\RabbitMqConnectionListener:
    tags:
      - name: kernel.event_listener
        event: kernel.terminate
        method: 'onKernelTerminate'
