parameters:

  # Affects how many elements can be returned in collection responses.
  pageSize:

    # Minimum number of elements which are always returned, if they exist.
    min: 5

    # Default number of elements which are returned if they exist.
    default: 25

    # Maximum number of elements which are returned in a single response. Should not be way more than 100, as
    # performance problems may arise.
    max: 100

  # Null can be replaced by links to redirect to external problem documentation sites.
  problemInstanceLinks:
    404-not-found: null

  # Handles the /register endpoint.
  register:

    # If true, the /register endpoint is active and anonymous users can create accounts.
    enabled: false

    # The property name of the identifier. Identifier must be unique across the API, usually the email.
    uniqueIdentifier: email

    # Either false or a regex for checking the identifier content.
    uniqueIdentifierRegex: false

  # Configures the /instance-configuration endpoint
  instanceConfiguration:

    # If true, enables the endpoint. If false, 403 error messages are returned.
    enabled: true

    # If false, the version number is omitted.
    showVersion: true

  token:

    # Minimum lifetime of created tokens.
    # 30 minutes.
    minLifetimeInSeconds: 1800

    # Default lifetime of created tokens.
    # 3 hours.
    defaultLifetimeInSeconds: 10800

    # Maximum lifetime of created tokens.
    # Can be set to false to disable maximum limit.
    # 13 months.
    maxLifetimeInSeconds: 34214400

    # Expired tokens will be deleted after at least x seconds.
    # Can be set to false to disable auto delete feature.
    # 14 days.
    deleteExpiredTokensAutomaticallyInSeconds: 1209600
