services:

  _defaults:
    autowire: true
    autoconfigure: true

  App\EventSystem\ElementDefragmentize\EventListener\GenericPropertyElementDefragmentizeEventListener:
    tags:
      - name: kernel.event_listener
        event: 'App\EventSystem\ElementDefragmentize\Event\NodeElementDefragmentizeEvent'
        method: 'onNodeElementDefragmentizeEvent'
      - name: kernel.event_listener
        event: 'App\EventSystem\ElementDefragmentize\Event\RelationElementDefragmentizeEvent'
        method: 'onRelationElementDefragmentizeEvent'

  App\EventSystem\ElementDefragmentize\EventListener\NodeElementDefragmentizeEventListener:
    tags:
      - name: kernel.event_listener
        event: 'App\EventSystem\ElementDefragmentize\Event\NodeElementDefragmentizeEvent'
        method: 'onNodeElementDefragmentizeEvent'

  App\EventSystem\ElementDefragmentize\EventListener\RelationElementDefragmentizeEventListener:
    tags:
      - name: kernel.event_listener
        event: 'App\EventSystem\ElementDefragmentize\Event\RelationElementDefragmentizeEvent'
        method: 'onRelationElementDefragmentizeEvent'
