services:

  _defaults:
    autowire: true
    autoconfigure: true

  App\EventSystem\Request\EventListener\ApiKeyCheckOnKernelRequestEventListener:
    tags:
      - name: kernel.event_listener
        event: 'kernel.request'
        method: 'onKernelRequest'

#  App\EventSystem\Request\EventListener\RouterListener:
#    arguments:
#      $matcher: '@router.default'


  App\EventSystem\Request\EventListener\LogRequestListener:
    arguments:
      $matcher: '@router.default'
    tags:
      - name: kernel.event_listener
        event: 'kernel.request'
        method: 'onKernelRequest'
      - name: kernel.event_listener
        event: 'kernel.response'
        method: 'onKernelResponse'
