services:

  _defaults:
    autowire: true
    autoconfigure: true

  App\EventSystem\ElementPropertyReset\EventListener\CreatedElementPropertyResetEventListener:
    tags:
      - name: kernel.event_listener
        event: 'App\EventSystem\ElementPropertyReset\Event\ElementPropertyResetEvent'
        method: 'onElementPropertyResetEvent'

  App\EventSystem\ElementPropertyReset\EventListener\IdElementPropertyResetEventListener:
    tags:
      - name: kernel.event_listener
        event: 'App\EventSystem\ElementPropertyReset\Event\ElementPropertyResetEvent'
        method: 'onElementPropertyResetEvent'

  App\EventSystem\ElementPropertyReset\EventListener\TokenElementPropertyResetEventListener:
    tags:
      - name: kernel.event_listener
        event: 'App\EventSystem\ElementPropertyReset\Event\ElementPropertyResetEvent'
        method: 'onElementPropertyResetEvent'

  App\EventSystem\ElementPropertyReset\EventListener\UpdatedElementPropertyResetEventListener:
    tags:
      - name: kernel.event_listener
        event: 'App\EventSystem\ElementPropertyReset\Event\ElementPropertyResetEvent'
        method: 'onElementPropertyResetEvent'

  App\EventSystem\ElementPropertyReset\EventListener\UserElementPropertyResetEventListener:
    tags:
      - name: kernel.event_listener
        event: 'App\EventSystem\ElementPropertyReset\Event\ElementPropertyResetEvent'
        method: 'onElementPropertyResetEvent'
